provision: postgresql
verify: rthallisey/service-broker-ci/wait-for-resource.sh create pod postgresql

provision: rthallisey/service-broker-ci/mediawiki123-apb
verify: rthallisey/service-broker-ci/wait-for-resource.sh create pod mediawiki

bind: postgresql
verify: rthallisey/service-broker-ci/wait-for-resource.sh create bindings.v1alpha1.servicecatalog.k8s.io binding
verify: rthallisey/service-broker-ci/verify-bind.sh mediawiki123

unbind: postgresql | mediawiki123-apb
verify: rthallisey/service-broker-ci/wait-for-resource.sh delete bindings.v1alpha1.servicecatalog.k8s.io binding

deprovision: postgresql
verify: rthallisey/service-broker-ci/wait-for-resource.sh delete instance postgresql

deprovision: rthallisey/service-broker-ci/mediawiki123-apb
verify: rthallisey/service-broker-ci/wait-for-resource.sh delete instance mediawiki
