provision: rhscl-postgresql-apb
provision: ansibleplaybookbundle/mediawiki123-apb

bind: rhscl-postgresql-apb
verify: rthallisey/service-broker-ci/verify-mediawiki-postgresql.sh
unbind: rhscl-postgresql-apb | mediawiki123-apb

deprovision: rhscl-postgresql-apb
deprovision: ansibleplaybookbundle/mediawiki123-apb
